# Generated by Django 5.1.5 on 2025-06-02 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('alimentacion', 'Alimentación Saludable'), ('monitoreo', 'Monitoreo del Crecimiento'), ('recetas', 'Recetas Nutritivas'), ('signos', 'Signos de Alerta')], max_length=20)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='analisis/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ancho_rostro', models.FloatField(blank=True, null=True)),
                ('distancia_interpupilar', models.FloatField(blank=True, null=True)),
                ('ratio_ojos_rostro', models.FloatField(blank=True, null=True)),
                ('ancho_mejillas', models.FloatField(blank=True, null=True)),
                ('ratio_mejillas_ojos', models.FloatField(blank=True, null=True)),
                ('signos_detectados', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('riesgo', 'Riesgo'), ('alerta', 'Alerta')], max_length=10)),
                ('recomendaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kids.analisisnutricional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
